[package]
name = "lttrs"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false